luac
fengari-lua/fengari-node-cli pull request #2
Opened 2017-08-10 09:59 UTC by giann

2017-08-10 11:52 UTC, daurnimator commented on package.json
> +	"scripts": {},
unrelated change?

2017-08-10 11:53 UTC, daurnimator commented on src/luac-cli.js
> +const lua      = require('../node_modules/fengari/src/lua.js');
Will these require paths work if someone does a 'global install' of this?

2017-08-10 12:14 UTC, giann commented on src/luac-cli.js
> +const lua      = require('../node_modules/fengari/src/lua.js');
Yes it works.
I also added the two binaries as `fengari` and `fengaric` in `package.json`.

You can test it with: `npm i -g fengari-lua/fengari-node-cli#luac`

2017-08-10 13:36 UTC, daurnimator commented on src/luac-cli.js
> +const lua      = require('../node_modules/fengari/src/lua.js');
I tried with:
```
sudo yarn global add fengari-lua/fengari-node-cli#luac
```

And it failed with:
```
$ fengaric
module.js:487
    throw err;
    ^

Error: Cannot find module '../node_modules/fengari/src/lua.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/fengari-node-cli/src/luac-cli.js:6:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

2017-08-10 13:44 UTC, giann commented on src/luac-cli.js
> +const lua      = require('../node_modules/fengari/src/lua.js');
Do you have any other fengari packages installed globally ?

2017-08-10 13:44 UTC, daurnimator commented on src/luac-cli.js
> +const lua      = require('../node_modules/fengari/src/lua.js');
Nope. That was the *only* node package I installed globally

2017-08-10 13:48 UTC, giann commented on src/luac-cli.js
> +const lua      = require('../node_modules/fengari/src/lua.js');
yarn install dependencies in a flat structure unlike npm it seems... not sure how to go around that

2017-08-11 15:25 UTC, daurnimator commented
Slight differences to luac.

examples:
```
 2 params, 14 slots, 3 upvalues, 12 locals, 19 constants, 0 functions
```
vs
```
 2 params, 14 slots, 3 upvalues, 12 locals, 19 constants, 0 function
```

```
 	22	[92]	EQ       	0 11 -10	; - "Author"
```
vs
```
 	22	[92]	EQ       	0 11 -10	; -"Author"
```

2017-08-11 15:25 UTC, daurnimator commented on src/luac-cli.js
> +const lua      = require('../node_modules/fengari/src/lua.js');
seems fixed now :)

2017-08-16 05:43 UTC, giann commented
Should be the same now

2017-08-16 09:27 UTC, daurnimator commented
Some differences:

```diff
-	46	[312]	DIV      	11 -5 11	; 1.0 -
+	46	[312]	DIV      	11 -5 11	; 1.0- 
```

```diff
-	20	[279]	SETTABLE 	8 -1 -1	; 1 1
+	20	[279]	SETTABLE 	8 -1 -1	; 11
```

```diff
-	12	[351]	CLOSURE  	4 0	; 0xa9ddb0
+	12	[351]	CLOSURE  	4 bx	; 0x39
```

```diff
-	22	[378]	MUL      	6 6 -2	; - 1e-06
+	22	[378]	MUL      	6 6 -2	; - 0.000001
```

2017-08-16 11:46 UTC, daurnimator requested changes

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +const PROGNAME = "luac";      /* default program name */
Should this be fengaric?

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +
random newline?

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +        return lua.to_luastring(FUNCTION);
Could you move the `lua.to_luastring` to outside this function?

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +        return lua.lua_topointer(L, -1).p;
Could we write a `toproto` helper function to match the C code better?

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +    return fs.writeSync(u, new Buffer(p), 0, size) > 0 ? 0 : 1;
Should this be `Buffer.from`?

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +            fatal(lua.to_jstring(lua.lua_tostring(L,-1)));
Use `lua_tojsstring`?

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +        fatal(lua.lua_tostring(L,-1));
Should this be `lua_tojsstring`?

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +                    print(`0x${c.toString(16)}`);
luac uses decimal escapes, not hex ones.

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +                if (lopcodes.getBMode(o) == lopcodes.OpArgU) print(` bx`);
missing interpolation

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +                    if (lopcodes.ISK(c)) PrintConstant(f, lopcodes.INDEXK(c));
Missing print of space before this line

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +                    else print("- ");
This print shouldn't have a space after the hyphen

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +                    else print("- ");
This print shouldn't have a space after the hyphen

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +        s = lua.to_luastring("(bstring");
missing close parenthesis

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +        s = lua.to_luastring("(string");
missing close parenthesis

2017-08-16 11:46 UTC, daurnimator commented on src/luac-cli.js
> +    PrintHeader(f);
Might as well use a var `n` like the C code

2017-08-16 12:06 UTC, giann commented on src/luac-cli.js
> +            fatal(lua.to_jstring(lua.lua_tostring(L,-1)));
Yes and `new Buffer` is even [deprecated](https://nodejs.org/api/buffer.html#buffer_new_buffer_array)

2017-08-16 12:18 UTC, giann commented on src/luac-cli.js
> +    return fs.writeSync(u, new Buffer(p), 0, size) > 0 ? 0 : 1;
Yes and `new Buffer` is even [deprecated](https://nodejs.org/api/buffer.html#buffer_new_buffer_array)

2017-08-16 13:36 UTC, daurnimator approved these changes

2017-08-16 13:36 UTC, daurnimator commented
Looks good now except for rendering of numbers; but that appears to be an issue with sprintf.js.

2017-08-16 13:37 UTC, merged